const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.nav-links');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
if('IntersectionObserver' in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));}

const params=new URLSearchParams(location.search);
function setIfOption(select,value){if(!select||!value)return;const ok=[...select.options].some(o=>o.value===value);if(ok)select.value=value;}

// Case Explorer — search + domain + management question + region + scope + industry + operating model + evidence tier.
const caseCards=[...document.querySelectorAll('.case-explorer-card')],caseSearch=document.querySelector('#case-search'),caseDomain=document.querySelector('#case-domain-filter'),caseQuestion=document.querySelector('#case-question-filter'),caseRegion=document.querySelector('#case-region-filter'),caseScope=document.querySelector('#case-scope-filter'),caseIndustry=document.querySelector('#case-industry-filter'),caseBusiness=document.querySelector('#case-business-filter'),caseEvidence=document.querySelector('#case-evidence-filter'),caseReset=document.querySelector('#case-reset-filter'),caseCount=document.querySelector('#case-result-count'),caseEmpty=document.querySelector('.case-filter-empty');
function applyCaseFilters(){if(!caseCards.length)return;const q=(caseSearch?.value||'').trim().toLowerCase(),dv=caseDomain?.value||'All',qv=caseQuestion?.value||'All',rv=caseRegion?.value||'All',sv=caseScope?.value||'All',iv=caseIndustry?.value||'All',bv=caseBusiness?.value||'All',ev=caseEvidence?.value||'All';let n=0;caseCards.forEach(c=>{const ok=(!q||(c.dataset.search||'').includes(q))&&(dv==='All'||(c.dataset.domains||'').split('|').includes(dv))&&(qv==='All'||(c.dataset.questions||'').split('|').includes(qv))&&(rv==='All'||(c.dataset.regions||'').split('|').includes(rv))&&(sv==='All'||c.dataset.scope===sv)&&(iv==='All'||c.dataset.industry===iv)&&(bv==='All'||(c.dataset.business||'').split('|').includes(bv))&&(ev==='All'||c.dataset.evidence===ev);c.hidden=!ok;if(ok)n++});if(caseCount)caseCount.textContent=String(n);if(caseEmpty)caseEmpty.hidden=n!==0;}
setIfOption(caseDomain,params.get('domain'));setIfOption(caseQuestion,params.get('question'));setIfOption(caseRegion,params.get('region'));setIfOption(caseScope,params.get('scope'));setIfOption(caseIndustry,params.get('industry'));setIfOption(caseBusiness,params.get('business'));setIfOption(caseEvidence,params.get('evidence'));if(caseSearch&&params.get('q'))caseSearch.value=params.get('q');
caseSearch?.addEventListener('input',applyCaseFilters);[caseDomain,caseQuestion,caseRegion,caseScope,caseIndustry,caseBusiness,caseEvidence].forEach(x=>x?.addEventListener('change',applyCaseFilters));caseReset?.addEventListener('click',()=>{if(caseSearch)caseSearch.value='';[caseDomain,caseQuestion,caseRegion,caseScope,caseIndustry,caseBusiness,caseEvidence].forEach(x=>{if(x)x.value='All'});history.replaceState(null,'',location.pathname);applyCaseFilters();});applyCaseFilters();

// Knowledge-map precise concept index.
const taxItems=[...document.querySelectorAll('.tax-explorer-item')],taxSearch=document.querySelector('#tax-search'),taxType=document.querySelector('#tax-type-filter'),taxStatus=document.querySelector('#tax-status-filter'),taxReset=document.querySelector('#tax-reset-filter'),taxCount=document.querySelector('#tax-result-count'),taxEmpty=document.querySelector('.tax-filter-empty');
function applyTaxFilters(){if(!taxItems.length)return;const q=(taxSearch?.value||'').trim().toLowerCase(),tv=taxType?.value||'All',sv=taxStatus?.value||'All';let n=0;taxItems.forEach(x=>{const ok=(!q||(x.dataset.search||'').includes(q))&&(tv==='All'||x.dataset.type===tv)&&(sv==='All'||x.dataset.status===sv);x.hidden=!ok;if(ok)n++});if(taxCount)taxCount.textContent=String(n);if(taxEmpty)taxEmpty.hidden=n!==0;}
taxSearch?.addEventListener('input',applyTaxFilters);[taxType,taxStatus].forEach(x=>x?.addEventListener('change',applyTaxFilters));taxReset?.addEventListener('click',()=>{if(taxSearch)taxSearch.value='';if(taxType)taxType.value='All';if(taxStatus)taxStatus.value='All';applyTaxFilters();});applyTaxFilters();

// Library Explorer — search + collection + knowledge domain.
const libCards=[...document.querySelectorAll('.resource-card')],libSearch=document.querySelector('#library-search'),libCollection=document.querySelector('#library-collection-filter'),libDomain=document.querySelector('#library-domain-filter'),libReset=document.querySelector('#library-reset-filter'),libCount=document.querySelector('#library-result-count'),libEmpty=document.querySelector('.library-filter-empty');
function applyLibraryFilters(){if(!libCards.length)return;const q=(libSearch?.value||'').trim().toLowerCase(),cv=libCollection?.value||'All',dv=libDomain?.value||'All';let n=0;libCards.forEach(c=>{const ok=(!q||(c.dataset.search||'').includes(q))&&(cv==='All'||c.dataset.collection===cv)&&(dv==='All'||(c.dataset.domains||'').split('|').includes(dv));c.hidden=!ok;if(ok)n++});if(libCount)libCount.textContent=String(n);if(libEmpty)libEmpty.hidden=n!==0;}
setIfOption(libCollection,params.get('collection'));setIfOption(libDomain,params.get('domain'));if(libSearch&&params.get('q'))libSearch.value=params.get('q');
libSearch?.addEventListener('input',applyLibraryFilters);[libCollection,libDomain].forEach(x=>x?.addEventListener('change',applyLibraryFilters));libReset?.addEventListener('click',()=>{if(libSearch)libSearch.value='';if(libCollection)libCollection.value='All';if(libDomain)libDomain.value='All';history.replaceState(null,'',location.pathname);applyLibraryFilters();});applyLibraryFilters();

// Improve current-page semantics and keyboard state for nav.
document.querySelectorAll('.nav-links a.active').forEach(a=>a.setAttribute('aria-current','page'));


// V1.3 full-site search — embedded index so it also works from local file:// previews.
const siteSearchInput=document.querySelector('#site-search-input'),siteSearchResults=document.querySelector('#site-search-results'),siteSearchCount=document.querySelector('#site-search-count'),siteSearchIndexEl=document.querySelector('#site-search-index'),siteSearchTypeBtns=[...document.querySelectorAll('.search-type-btn')];
let siteSearchType='All',siteSearchIndex=[];
try{siteSearchIndex=JSON.parse(siteSearchIndexEl?.textContent||'[]')}catch(e){siteSearchIndex=[]}
function escHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderSiteSearch(){if(!siteSearchInput||!siteSearchResults)return;const q=siteSearchInput.value.trim().toLowerCase();if(!q){siteSearchResults.innerHTML='<div class="site-search-empty">输入关键词后开始搜索。</div>';if(siteSearchCount)siteSearchCount.textContent='0';return;}const terms=q.split(/\s+/).filter(Boolean);const rows=siteSearchIndex.filter(x=>(siteSearchType==='All'||x.type===siteSearchType)&&terms.every(t=>((x.title+' '+x.text).toLowerCase()).includes(t))).slice(0,80);if(siteSearchCount)siteSearchCount.textContent=String(rows.length);siteSearchResults.innerHTML=rows.length?rows.map(x=>`<a class="site-search-result" href="${escHtml(x.url)}" ${x.external?'target="_blank" rel="noopener"':''}><span>${escHtml(x.type)}</span><b>${escHtml(x.title)}</b><p>${escHtml((x.text||'').slice(0,180))}${(x.text||'').length>180?'…':''}</p></a>`).join(''):'<div class="site-search-empty">没有找到匹配内容。可以换一个企业名、地区或经营问题试试。</div>';}
siteSearchInput?.addEventListener('input',renderSiteSearch);siteSearchTypeBtns.forEach(b=>b.addEventListener('click',()=>{siteSearchTypeBtns.forEach(x=>x.classList.remove('active'));b.classList.add('active');siteSearchType=b.dataset.type||'All';renderSiteSearch()}));if(siteSearchInput){const q=new URLSearchParams(location.search).get('q');if(q){siteSearchInput.value=q;renderSiteSearch()}else renderSiteSearch();}
